USE Championship;
GO

DROP TABLE IF EXISTS Players;

CREATE TABLE Players (
	id INT CONSTRAINT PK_Players_id PRIMARY KEY IDENTITY (1, 1),
	[name] VARCHAR(45) NOT NULL,
	surname VARCHAR(45) NOT NULL,
	birthday DATE NOT NULL,
	country VARCHAR(45) NOT NULL,
	cost INT NOT NULL,
	
);
